#
# Copyright(c) 2025 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

[build-system]
requires = ["setuptools>=42", "wheel", "Cython", "numpy", "torch==2.10.0"]
build-backend = "setuptools.build_meta"

[project]
name = "midgard"
description = "A comprehensive tool for articulated asset generation with advanced features."
authors = [
    { name = "Intel XRL - eXtended Reality Laboratory" },
]
maintainers = [
    { name = "Quentin Leboutet", email = "quentin.leboutet@intel.com" },
    { name = "Nina Wiedermann", email = "nina.wiedermann@intel.com" },
    { name = "Kai Yuan", email = "kai.yuan@intel.com" },
]

dependencies = [
    "black >= 24.4",
]

license = { file = "LICENSE" }
readme = "README.md"
keywords = ["machine learning", "asset generation", "geometry"]
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 4 - Beta",

    # Indicate who your project is intended for
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",

    # License
    "License :: OSI Approved :: MIT License",

    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">= 3.10"
dynamic = ["version"]

[project.urls]
Homepage = "https://quentin-leboutet.github.io/MIDGArD/"
Documentation = "https://github.com/isl-org/MIDGArD/MIDGArD/blob/main/README.md"
Repository = "https://github.com/isl-org/MIDGArD/MIDGArD"

[tool.setuptools]
py-modules = ["articulated_asset_generation"]
 
[tool.black]
include = 'core/.*py|tests/.*py|scripts/.*py' 
